# Generated by Django 4.2 on 2025-10-05 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد شاخص')),
                ('name', models.CharField(max_length=255, verbose_name='نام شاخص')),
                ('evaluation_period', models.CharField(choices=[('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('semiannual', 'شش ماهه'), ('annual', 'سالانه')], max_length=20, verbose_name='دوره ارزیابی')),
                ('unit', models.CharField(choices=[('day', 'روز'), ('percent', 'درصد'), ('count', 'تعداد'), ('million_rial', 'میلیون ریال'), ('billion_rial', 'میلیارد ریال'), ('toman', 'تومان'), ('other', 'سایر')], max_length=50, verbose_name='واحد سنجش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to=settings.AUTH_USER_MODEL, verbose_name='مالک شاخص')),
            ],
            options={
                'verbose_name': 'شاخص',
                'verbose_name_plural': 'شاخص\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ActiveMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')])),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'ماه فعال',
                'verbose_name_plural': 'ماه\u200cهای فعال',
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مقدار واقعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='indicators.indicator', verbose_name='شاخص')),
            ],
            options={
                'verbose_name': 'داده شاخص',
                'verbose_name_plural': 'داده\u200cهای شاخص\u200cها',
                'ordering': ['-year', '-month'],
                'unique_together': {('indicator', 'month', 'year')},
            },
        ),
    ]
