# Generated by Django 4.2 on 2025-10-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('annual_target', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='هدف سالانه')),
                ('jan_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='فروردین')),
                ('feb_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='اردیبهشت')),
                ('mar_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='خرداد')),
                ('apr_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='تیر')),
                ('may_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مرداد')),
                ('jun_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='شهریور')),
                ('jul_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مهر')),
                ('aug_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='آبان')),
                ('sep_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='آذر')),
                ('oct_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='دی')),
                ('nov_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='بهمن')),
                ('dec_target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='اسفند')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='indicators.indicator', verbose_name='شاخص')),
            ],
            options={
                'verbose_name': 'هدف شاخص',
                'verbose_name_plural': 'اهداف شاخص\u200cها',
                'ordering': ['indicator', 'year'],
                'unique_together': {('indicator', 'year')},
            },
        ),
    ]
